<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<?php
		$this->getCSS('bootstrap.min'); 
		$this->getCSS('font-awesome.min'); 
    //$this->getCSS('exteds');
    $this->getCSS('okystyles');
    $this->getFavicon();
	?>
  <link rel='stylesheet' type='text/css' href='http://fonts.googleapis.com/css?family=Fjord+One'>
  <link rel='stylesheet' type='text/css' href='http://fonts.googleapis.com/css?family=Raleway'>
</head>
<body>

  
  <div class="mnuMain">
    <div class="oLogo">&nbsp;</div>
    <ul class="btnTopbar">
      <li>Cerrar sesi&oacute;n</li>
      <li>Preferencias</li>
      <li>opcion3</li>
      <li>Perfil</li>
    </ul>
    
  </div>
  
  <div id="mnuPanel">
    
    <img src="assets/img/core/small/icowoman.png" class="userphoto">
    
    <label>Omar Lee Paba ching</label>
    <label>Administrator</label>
    <label>07/11/14 10:30 am</label>
    <br/>
    <label>Config</label>
    <label > Omar Lee Paba ching - 909020142</label>
    

  </div>

  <div id="divContent">
    <div id="otabs">
      <ul class="titles">
        <li class="active">
          <i class="glyphicon glyphicon-home icontab"></i>
          <center class="titletab">Inicio</center>
        </li>
        <li>
          <i class="glyphicon glyphicon-home icontab"></i>
          <center class="titletab">Terceros</center>
        </li>
        <li>
          <i class="glyphicon glyphicon-home icontab"></i>
          <center class="titletab">Inicio</center>
        </li>
        <li>
          <i class="glyphicon glyphicon-home icontab"></i>
          <center class="titletab">Inicio</center>
        </li>
        <li>
          <i class="glyphicon glyphicon-home icontab"></i>
          <center class="titletab">Inicio</center>
        </li>
        <li>
          <i class="glyphicon glyphicon-home icontab"></i>
          <center class="titletab">Balances</center>
        </li>
        <li>
          <i class="glyphicon glyphicon-tasks icontab"></i>
          <center class="titletab">Config.</center>
        </li>

      </ul>
    </div>
    <div class="opanel">
      <div class="opanel-body">Contenido del opanel</div>
    </div>
    <div class="opanel">
      <div class="opanel-heading">
        <div class="title">
          <i class="glyphicon glyphicon-home"> </i> 
          <label>Panel heading without title</label>
        </div>
        <!-- div class="titleclose"></div -->
        <div class="glyphicon glyphicon-chevron-down closepanel"></div>
      </div>
        <div class="opanel-body">

        <form class="oform">
          <span>
            <label for="nombre">Identificación:</label>
            <input id="nombre" name="nombre" value="ingrese nombre" placeholder="Enter email">
          </span>
          
          <span>
            <label for="nombre">Nombres:</label>
            <input id="nombre" name="nombre">
          </span>
          
          <span>
            <label for="nombre">Apellidos</label>
            <input id="nombre" name="nombre">
          </span>
          
          <span>
            <label>Color:</label>
            <select>
              <option>Amarillo</option>
              <option>Amarillo</option>
              <option>Amarillo</option>
              <option>Amarillo</option>
              <option>Amarillo</option>
              <option>Amarillo</option>
              <option>Amarillo</option>
              <option>Amarillo</option>
              <option>Amarillo</option>
            </select>
          </span>

          <span>
            <label for="nombre">Digite el nombre del Usuario</label>
            <input id="nombre" name="nombre">
          </span>

          <span>
            <label for="nombre">Digite el nombre del Usuario2</label>
            <input id="nombre" name="nombre">
          </span>
          
          <br/>
          
          <span>
            <button>Aceptar</button>
            <button>Cancelar</button>
          </span>
        </form>
      </div>  
      <div class="opanel-body">
        <span>asdasdassd</span>
      </div>      
    </div>
  </div>
  <!-- script src="http://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="js/custom.js"></script -->

	<?php
		$this->getJS("libs/jquery.min");
		$this->getJS("libs/underscore-min");
		$this->getJS("libs/bootstrap.min");
		$this->getJS("libs/handlebars.min");
		//$this->getJS("libs/ember.min");
    //$this->getJS('exteds');
		//$this->getJS("app");
	?>
</body>
</html>