<div class="row">
	
	<div class="col-md-4">
		<div class="opanel">
			<div class="opanel-heading">
				<div class="title">
					<i class="glyphicon glyphicon-home"> </i> 
					<label>Categorias</label>
				</div>
				<!-- div class="titleclose"></div -->
				<div class="glyphicon glyphicon-chevron-down closepanel"></div>
			</div>
			<div class="opanel-body">
				primer contenido
			</div>
			<div class="opanel-body">
      			<span>asdasdassd</span>
      		</div>
		</div>
	</div>
	
	<div class="col-md-3">
		<div class="opanel">
			<div class="opanel-heading">
				<div class="title">
					<i class="glyphicon glyphicon-home"> </i> 
					<label>Panel heading without title</label>
				</div>
				<!-- div class="titleclose"></div -->
				<div class="glyphicon glyphicon-chevron-down closepanel"></div>
			</div>
			<div class="opanel-body">
				primer contenido
			</div>
			<div class="opanel-body">
      			<span>asdasdassd</span>
      		</div>
		</div>
	</div>

	<div class="col-md-3">
		<div class="opanel">
			<div class="opanel-heading">
				<div class="title">
					<i class="glyphicon glyphicon-home"> </i> 
					<label>Panel heading without title</label>
				</div>
				<!-- div class="titleclose"></div -->
				<div class="glyphicon glyphicon-chevron-down closepanel"></div>
			</div>
			<div class="opanel-body">
				primer contenido
			</div>
			<div class="opanel-body">
      			<span>asdasdassd</span>
      		</div>
		</div>
	</div>
		
</div>

<div class="row">
	<div class="col-md-12">
		<div class="opanel">
			<div class="opanel-heading">
				<div class="title">
					<i class="glyphicon glyphicon-home"> </i> 
					<label>Existencias</label>
				</div>
			</div>
			<div class="opanel-body" style="height: 320px;">
				<table class="table">
					<thead>
						<th>Codigo</th>
						<th>Nombre</th>
						<th>Estado</th>
						<th>Cantidad</th>
						<th>Costo</th>
						<th>Valor</th>
					</thead>
					<tbody>
						<?php for($i = 0; $i < 60; $i++){ ?>
						<tr>
							<td>123456789012</td>
							<td>Bolso de Tela Color Marrón</td>
							<td>Activo</td>
							<td> 999</td>
							<td>$ 99.999.99.00</td>
							<td>$ 99.999.99.00</td>
						</tr>
						<?php } ?>
					</tbosy>
				</table>
			</div>
		</div>
	</div>	
</div>
