<div class="row">
	
	<div class="col-md-3">
		<div class="opanel">
			<div class="opanel-heading">
				<div class="title">
					<i class="glyphicon glyphicon-home"> </i> 
					<label>Categorias</label>
				</div>
				<!-- div class="titleclose"></div -->
				<div class="glyphicon glyphicon-chevron-down closepanel"></div>
			</div>
			<div class="opanel-body">
				<table class="table_slim">
					<thead>
						<tr>
							<th style="width: 20px;">Id</th>
							<th style="width: *%;">Nommbre</th>
							<!-- <th style="width: 80px;">Sub.</th> -->
						</tr>
					</thead>
					<tbody>
					<?php
						foreach ($this->allCategories as $cat){
							echo '<tr>';
							echo '<td>'.$cat['id'].'</td>';
							echo '<td>'.$cat['name'].'</td>';
							/*echo '<td>$ 99.999.999</td>';*/
							echo '</tr>	';
						}	
					?>
					</tbody>
				</table>
			</div>
			<div class="opanel-body">
      			<span style="float: right"><?php echo count($this->allCategories) . ' Categorias'; ?></span>
      		</div>
		</div>
	</div>
	
	<div class="col-md-3">
		<div class="opanel">
			<div class="opanel-heading">
				<div class="title">
					<i class="glyphicon glyphicon-home"> </i> 
					<label>Mas vendidos mes anterior</label>
				</div>
				<!-- div class="titleclose"></div -->
				<div class="glyphicon glyphicon-chevron-down closepanel"></div>
			</div>
			<div class="opanel-body">
				primer contenido
			</div>
			<div class="opanel-body">
      			<span>asdasdassd</span>
      		</div>
		</div>
	</div>

	<div class="col-md-3">
		<div class="opanel">
			<div class="opanel-heading">
				<div class="title">
					<i class="glyphicon glyphicon-home"> </i> 
					<label>Subcategorias</label>
				</div>
				<!-- div class="titleclose"></div -->
				<div class="glyphicon glyphicon-chevron-down closepanel"></div>
			</div>
			<div class="opanel-body">
				primer contenido
			</div>
			<div class="opanel-body">
      			<div style="float: right">asdasdassd</div>
      		</div>
		</div>
	</div>

	<div class="col-md-3">
		<div class="opanel">
			<div class="opanel-heading">
				<div class="title">
					<i class="glyphicon glyphicon-home"> </i> 
					<label>Articulos sin Existencias</label>
				</div>
				<!-- div class="titleclose"></div -->
				<div class="glyphicon glyphicon-chevron-down closepanel"></div>
			</div>
			<div class="opanel-body">
				primer contenido
			</div>
			<div class="opanel-body">
      			<span>asdasdassd</span>
      		</div>
		</div>
	</div>
		
</div>

<div class="row">
	<div class="col-md-12">
		<div class="opanel">
			<div class="opanel-heading">
				<div class="title">
					<i class="glyphicon glyphicon-home"> </i> 
					<label>Existencias</label>
				</div>
			</div>
			<div class="opanel-body" style="height: 320px;">
				<table class="table">
					<thead>
						<th>Codigo</th>
						<th>Nombre</th>
						<th>Estado</th>
						<th>Cantidad</th>
						<th>Costo</th>
						<th>Valor</th>
					</thead>
					<tbody>
						<?php for($i = 0; $i < 60; $i++){ ?>
						<tr>
							<td>123456789012</td>
							<td>Bolso de Tela Color Marrón</td>
							<td>Activo</td>
							<td> 999</td>
							<td>$ 99.999.99.00</td>
							<td>$ 99.999.99.00</td>
						</tr>
						<?php } ?>
					</tbosy>
				</table>
			</div>
		</div>
	</div>	
</div>
