<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<?php
		$this->getCSS('bootstrap.min'); 
		$this->getCSS('font-awesome.min'); 
    //$this->getCSS('exteds');
    $this->getCSS('okystyles');
    $this->getFavicon();
    $this->googleFont('Fjord+One');
    $this->googleFont('Raleway');
	?>
</head>
<body>

  
  <div class="mnuMain">
    <div class="oLogo" style="text-align: center; "><img src="assets/img/core/logo.png"></div>
    <ul class="btnTopbar">
      <li>Cerrar sesi&oacute;n</li>
      <li>Preferencias</li>
      <li>opcion3</li>
      <li>Perfil</li>
    </ul>
    
  </div>
  
  <div id="mnuPanel">
    
    <img src="assets/img/core/small/icoMan.png" class="userphoto">
    
    <label>Omar Lee Paba ching</label>
    <label>Administrator</label>
    <label>07/11/14 10:30 am</label>
    <br/>
    <label>Config</label>
    <label > Omar Lee Paba ching - 909020142</label>
    

  </div>

  <div id="divContent">
    <div id="otabs">
      <ul class="titles">
        <?php $this->limenu('Dashboard'); ?>
          <a href="<?php $this->getPath('dashboard'); ?>">
            <i class="glyphicon glyphicon-dashboard icontab"></i>
            <center class="titletab">Dashboard</center>
            </a>
        </li>
        <?php $this->limenu('Invoices'); ?>
          <a href="<?php $this->getPath('invoices'); ?>">
            <i class="glyphicon glyphicon-list-alt icontab"></i>
            <center class="titletab">Facturación</center>
          </a>
        </li>
        <?php $this->limenu('Stock'); ?>
          <a href="<?php $this->getPath('stocks'); ?>">
            <i class="glyphicon glyphicon-barcode icontab"></i>
            <center class="titletab">Inventario</center>
          </a>
        </li>
        <?php $this->limenu('Peoples'); ?>
          <i class="glyphicon glyphicon-home icontab"></i>
          <center class="titletab">Terceros</center>
        </li>
        <?php $this->limenu('Reports'); ?>
          <i class="glyphicon glyphicon-signal icontab"></i>
          <center class="titletab">Reportes</center>
        </li>
        <?php $this->limenu('Balances'); ?>
          <i class="glyphicon glyphicon-tasks icontab"></i>
          <center class="titletab">Balances</center>
        </li>
        <?php $this->limenu('Config'); ?>
          <i class="fa fa-cogs icontab"></i>
          <center class="titletab">Config.</center>
        </li>

      </ul>
    </div>
    <div class="opanels">
      <?php $this->renderContent(); ?>
    </div>  <!-- Fin Opanels -->
  </div>
  <!-- script src="http://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="js/custom.js"></script -->

	<?php
		$this->getJS("libs/jquery.min");
		$this->getJS("libs/underscore-min");
		$this->getJS("libs/bootstrap.min");
		$this->getJS("libs/handlebars.min");
		//$this->getJS("libs/ember.min");
    //$this->getJS('exteds');
		//$this->getJS("app");
	?>
</body>
</html>