    <div class="opanel">
      <div class="opanel-heading">
        <div class="title">
          <i class="glyphicon glyphicon-home"> </i> 
          <label>Panel heading without title</label>
        </div>
        <!-- div class="titleclose"></div -->
        <div class="glyphicon glyphicon-chevron-down closepanel"></div>
      </div>
        <div class="opanel-body">

        <form class="oform">
          <span>
            <label for="nombre">Identificación:</label>
            <input id="nombre" name="nombre" value="ingrese nombre" placeholder="Enter email">
          </span>
          
          <span>
            <label for="nombre">Nombres:</label>
            <input id="nombre" name="nombre">
          </span>
          
          <span>
            <label for="nombre">Apellidos</label>
            <input id="nombre" name="nombre">
          </span>
          
          <span>
            <label>Color:</label>
            <select>
              <option>Amarillo</option>
              <option>Amarillo</option>
              <option>Amarillo</option>
              <option>Amarillo</option>
              <option>Amarillo</option>
              <option>Amarillo</option>
              <option>Amarillo</option>
              <option>Amarillo</option>
              <option>Amarillo</option>
            </select>
          </span>

          <span>
            <label for="nombre">Digite el nombre del Usuario</label>
            <input id="nombre" name="nombre">
          </span>

          <span>
            <label for="nombre">Digite el nombre del Usuario2</label>
            <input id="nombre" name="nombre">
          </span>
          
          <br/>
          
          <span>
            <button>Aceptar</button>
            <button>Cancelar</button>
          </span>
        </form>
      </div>  
      <div class="opanel-body">
        <span>asdasdassd</span>
      </div>      
    </div>